version: '3.1'

services:
  web:
    image: odoo:17  # 使用最新版本的 Odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo  # 確保掛載了 config 目錄
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]

  db:
    image: postgres:15  # 使用最新版本的 Postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  odoo-web-data:
  odoo-db-data:
